package org.openapitools.model;

import java.net.URI;
import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonSubTypes;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.model.Aliases;
import org.openapitools.model.ComplexSubject;
import org.openapitools.model.ComplexSubjectApplication;
import org.openapitools.model.ComplexSubjectDevice;
import org.openapitools.model.ComplexSubjectGroup;
import org.openapitools.model.ComplexSubjectOrgUnit;
import org.openapitools.model.ComplexSubjectSession;
import org.openapitools.model.ComplexSubjectTenant;
import org.openapitools.model.ComplexSubjectUser;
import org.openapitools.model.SimpleSubject;
import org.openapitools.jackson.nullable.JsonNullable;
import java.time.OffsetDateTime;
import javax.validation.Valid;
import javax.validation.constraints.*;
import io.swagger.v3.oas.annotations.media.Schema;


import java.util.*;
import javax.annotation.Generated;


@JsonIgnoreProperties(
  value = "format", // ignore manually set format, it will be automatically generated by Jackson during serialization
  allowSetters = true // allows the format to be set during deserialization
)
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "format", visible = true)
@JsonSubTypes({
  @JsonSubTypes.Type(value = AddSubjectParametersSubject.class, name = "AddSubjectParameters_subject"),
  @JsonSubTypes.Type(value = Aliases.class, name = "Aliases"),
  @JsonSubTypes.Type(value = ComplexSubject.class, name = "ComplexSubject"),
  @JsonSubTypes.Type(value = RemoveSubjectParametersSubject.class, name = "RemoveSubjectParameters_subject"),
  @JsonSubTypes.Type(value = SimpleSubject.class, name = "SimpleSubject"),
  @JsonSubTypes.Type(value = StreamStatusSubject.class, name = "StreamStatus_subject"),
  @JsonSubTypes.Type(value = TriggerEventParametersSubject.class, name = "TriggerEventParameters_subject")
})

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2023-05-24T15:10:11.030458Z[Etc/UTC]")
public interface Subject {
    public String getFormat();
}
